# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 曹建峰的博客
email: windcao@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://caojianfeng.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: caojianfeng
redirect_to:
  - http://caojianfeng.com
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
#  - jekyll-paginate
#  - jekyll-multiple-languages

# 多语言配置{
#gems:           ['jekyll-multiple-languages']
# 如果需要分页, 请加入 jekyll-paginate 并放于 jekyll-multiple-languages 之前
# gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

# 所有的语言
#languages:          ['en', 'cn']

# 默认语言
# 如果没有配置，languages 中的第一项就是默认语言
#language_default:   'cn'
# 多语言配置}

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - preview.sh